rpc:
  name: crpc
  version: 1.0.2
  serverPort: 8090
  mock: false
  serializer: kryo
  registryConfig:
    registry: zookeeper
    address: localhost:2181
  loadBalancer: consistentHash  # fixme 负载均衡策略不是rpc框架指定吗？为什么这里可以指定？
  retryStrategy: fixedInterval
  tolerantStrategy: failOver